name: Test

on:

  workflow_dispatch:


jobs:
  tests:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: python -c "import os; print(os.getcwd())"

